version: '3.6'
services:
  postgres:
    container_name: postgres_hasura
    image: postgres:14.5
    restart: always
    volumes:
      - ~/storage/hasura/postgres:/data/postgres
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: hasura
      POSTGRES_USER: hasura
      POSTGRES_PASSWORD: hasura
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    networks:
      hasura:
        ipv4_address: 192.52.1.10

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@192.52.1.10:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: 102030
      HASURA_GRAPHQL_JWT_SECRET: "{\"type\": \"RS512\", \"key\": \"-----BEGIN CERTIFICATE-----\\nMIIDDTCCAfWgAwIBAgIJWqt1e9xiOH88MA0GCSqGSIb3DQEBCwUAMCQxIjAgBgNV\\nBAMTGWRldi1reXlkYmx3cy51cy5hdXRoMC5jb20wHhcNMjEwNTA1MTEzMzE2WhcN\\nMzUwMTEyMTEzMzE2WjAkMSIwIAYDVQQDExlkZXYta3l5ZGJsd3MudXMuYXV0aDAu\\nY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyUPWKeD73k0DRp0w\\n3ISlX49itIsBlt1LN/pw9bO1ynEJ0BbC3NAce8lyzzXbsIkfbn1BbAcfDHVYcn3/\\ngsEJrYjlTJMGNTisDbhTrM+TOoR+LrzF9BcVIjLpp3kxjy4iGG3qWfdukg+/Jh+T\\nPn7LCItzLvWxmScg3uet7xWVCx1Hoj8p7bpPeNvi6loOP5ucCwrSY59fnC4ExNPr\\nw8BJPS4JLwr1x4Y+0lB1CGkhePIka9TxDSdfHIpw2XRFX/f1b0D7TH0l+hrxsxgJ\\nPQstOV33GxkN3kaDGU+lsqZbr0q8smlHOEoERRbAzP8+jtrM6O971UNRWJVzqiva\\niYQz6QIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSsT6Ju4Jir\\nIY4WZEonvB4zdxN8KTAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEB\\nAKQdWnf0u7f092Xz/V14v9L72v4hB1XopgN83Nfz9P8wdHchm6JbmvpR3t2PGkyf\\nwULxQ4+F0Ux+7gZosH7SRQQbL1fW1VWFxh3jqELbT+hET4CrHRGSFu1Hd5bfylRq\\nVgnFR71QjgoBqNBxq9MxHu62UWb4orjvshAhhfnVN77eejurU3soaIAeZdK2KQ9A\\nfX7265UecpRGzpo3BbkT8Zo/T/ZYp7abJYp3YW0RLUJJqC3+nIMHndJSPuzlcmvG\\n+kJSNnOqsGDbjsM+PunkJI5FTyKsxZAsjZitxewRKHCQGz/DRmahyqNKAcfoYnYg\\nYk+seZ9MnbRRIWrYYBeNa/Y=\\n-----END CERTIFICATE-----\"}"
    networks:
      hasura:
        ipv4_address: 192.52.1.11

volumes:
  db_data:


networks:
  hasura:
    ipam:
      driver: default
      config:
        - subnet: 192.52.0.0/16
