version: '3.6'
services:
  postgres:
    container_name: postgres_hasura
    image: postgres:14.5
    restart: always
    volumes:
      - ~/storage/hasura/postgres:/data/postgres
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: hasura
      POSTGRES_USER: hasura
      POSTGRES_PASSWORD: hasura
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
    networks:
      hasura:
        ipv4_address: 192.52.1.10

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@192.52.1.10:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: "#nvU!Q7xjf!mnMlX1j0JzcmD7jpXW7KsV8szMKg#Y3*2yFq%D9"
    networks:
      hasura:
        ipv4_address: 192.52.1.11

volumes:
  db_data:


networks:
  hasura:
    ipam:
      driver: default
      config:
        - subnet: 192.52.0.0/16
